openapi: 3.0.1
info:
  title: Boiler Plate API
  description: Boiler Plate API
  version: 0.0.1
servers:
- url: http://localhost:8080
- url: https://hosting-not-yet
tags: []
paths:
  /auths/login:
    post:
      tags:
      - Auth
      summary: ë¡œê·¸ì¸
      description: '- ë¡œê·¸ì¸ ì…ë‹ˆë‹¤.'
      operationId: api_ë¡œê·¸ì¸
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/LoginRequestDto"
            examples:
              api_ë¡œê·¸ì¸:
                value: "{\"loginId\":\"test1\",\"password\":\"test1@1234\"}"
      responses:
        "200":
          description: "200"
          headers:
            Authorization:
              description: ì—‘ì„¸ìŠ¤ í† í°
              schema:
                type: string
            Set-Cookie:
              description: ì¬ë°œê¸‰ í† í°
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponseDto"
              examples:
                api_ë¡œê·¸ì¸:
                  value: |-
                    {
                      "message" : "OK",
                      "data" : null
                    }
  /auths/logout:
    post:
      tags:
      - Auth
      summary: ë¡œê·¸ì•„ì›ƒ
      description: '- ë¡œê·¸ì•„ì›ƒ ì…ë‹ˆë‹¤.'
      operationId: api_ë¡œê·¸ì•„ì›ƒ
      parameters:
      - name: Authorization
        in: header
        description: ì—‘ì„¸ìŠ¤ í† í°
        required: true
        schema:
          type: string
        example: accessabcdefghijklmnopqrstuvwxyz
      responses:
        "200":
          description: "200"
          headers:
            Set-Cookie:
              description: ì¿ í‚¤ ë¬´íš¨í™”
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/auths-reissue515442717"
              examples:
                api_ë¡œê·¸ì•„ì›ƒ:
                  value: |-
                    {
                      "message" : "OK",
                      "data" : null
                    }
  /auths/reissue:
    post:
      tags:
      - Auth
      summary: ì¬ë°œê¸‰
      description: '- ì¬ë°œê¸‰ ì…ë‹ˆë‹¤.'
      operationId: api_ì¬ë°œê¸‰
      parameters:
      - name: Authorization
        in: header
        description: ì—‘ì„¸ìŠ¤ í† í°
        required: true
        schema:
          type: string
        example: accessabcdefghijklmnopqrstuvwxyz
      responses:
        "200":
          description: "200"
          headers:
            Authorization:
              description: ì—‘ì„¸ìŠ¤ í† í°
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/auths-reissue515442717"
              examples:
                api_ì¬ë°œê¸‰:
                  value: |-
                    {
                      "message" : "OK",
                      "data" : null
                    }
  /health:
    get:
      tags:
      - "[Team Workspace]"
      summary: íŒ€ í˜‘ì—…ì„ ìœ„í•œ ê³µìš© ì •ë³´
      description: |
        ### TEAM ê³µìš© ê³µê°„

        ì„œë²„ì˜ ê¸°ë³¸ ìƒíƒœë¥¼ í™•ì¸í•˜ê³ , API ë¬¸ì„œ ì‚¬ìš© ë°©ì‹ê³¼ ê³µìš© ë§í¬ ë° ì—ëŸ¬ ì •ì˜ë¥¼ ì œê³µí•©ë‹ˆë‹¤.

        ---

        ### ğŸ”§ API ë¬¸ì„œ ì‚¬ìš©ë²•

        <details>
        <summary><strong>View</strong></summary>

        #### 1. í† í° ì‚¬ìš©ë²•
        ë¡œê·¸ì¸ í›„ ì‘ë‹µëœ JWT í† í°ì„ ë³µì‚¬í•´ì£¼ì„¸ìš”.

        1. Swagger ìš°ì¸¡ ìƒë‹¨ì˜ **Authorize** ë²„íŠ¼ì„ í´ë¦­í•©ë‹ˆë‹¤.
        2. `value` ì…ë ¥ë€ì— ë³µì‚¬í•œ í† í°(`Bearer {token}` í˜•ì‹)ì„ ë¶™ì—¬ë„£ê³  ì €ì¥í•©ë‹ˆë‹¤.
        3. ì´ì œ ëª¨ë“  ìš”ì²­ì€ í•´ë‹¹ JWTê°€ ìë™ í¬í•¨ë˜ì–´ ì „ì†¡ë©ë‹ˆë‹¤.

        <br>

        #### 2. ìš”ì²­ ì„œë²„ ë³€ê²½
        Swagger ì¢Œì¸¡ ìƒë‹¨ì˜ **Servers** í•­ëª©ì—ì„œ ìš”ì²­í•  ì„œë²„ë¥¼ ì„ íƒí•  ìˆ˜ ìˆìŠµë‹ˆë‹¤.

        </details>

        ---

        ### ğŸ”— ë§í¬

        <details>
        <summary><strong>View</strong></summary>

        - [Github Repository ë°”ë¡œê°€ê¸°](https://github.com/fprh13/boiler-plate-project)

        </details>

        ---

        ### â— ERROR ì •ì˜

        <details>
        <summary><strong>View</strong></summary>

        | HttpStatus | ì„¤ëª… | í•´ê²°ë°©ë²• |
        |-----------|------|----------|
        | **400 Bad Request** | í´ë¼ì´ì–¸íŠ¸ ìš”ì²­ ë°ì´í„°ê°€ ì˜ëª»ëœ ê²½ìš°ì…ë‹ˆë‹¤. | ìš”ì²­ ë°ì´í„°ì˜ ìœ íš¨ ê°’ì„ í™•ì¸í•´ì£¼ì„¸ìš”. |
        | **401 Unauthorized** | ì¸ì¦ ì •ë³´ê°€ ì—†ê±°ë‚˜ ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤. | ë¡œê·¸ì¸ í›„ ë°œê¸‰ëœ JWTë¥¼ ì „ì†¡í•´ì£¼ì„¸ìš”. |
        | **403 Forbidden** | í˜„ì¬ ê¶Œí•œìœ¼ë¡œëŠ” ìì›ì— ì ‘ê·¼í•  ìˆ˜ ì—†ìŠµë‹ˆë‹¤.<br>(ì˜ˆ: USER ê¶Œí•œì´ ADMIN ì „ìš© API ì ‘ê·¼ ì‹œ) | ìš”ì²­ ìì›ì— ë§ëŠ” ê¶Œí•œìœ¼ë¡œ ìš”ì²­í•´ì£¼ì„¸ìš”. |
        | **404 Not Found** | ìš”ì²­í•œ ë°ì´í„°ë¥¼ ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤. | ìš”ì²­í•œ IDë‚˜ ê²½ë¡œê°€ ì˜¬ë°”ë¥¸ì§€ í™•ì¸í•´ì£¼ì„¸ìš”. |
        | **405 Method Not Allowed** | ì§€ì›í•˜ì§€ ì•ŠëŠ” HTTP ë©”ì„œë“œë¡œ ìš”ì²­í–ˆìŠµë‹ˆë‹¤. | ì§€ì›í•˜ëŠ” HTTP Methodë¥¼ ì‚¬ìš©í•´ì£¼ì„¸ìš”. |
        | **409 Conflict** | ë¦¬ì†ŒìŠ¤ ì¶©ëŒ(ì¤‘ë³µ ë°ì´í„°) ë°œìƒ | ì¤‘ë³µ ì—¬ë¶€ë¥¼ í™•ì¸ í›„ ìš”ì²­í•´ì£¼ì„¸ìš”. |
        | **500 Internal Server Error** | ì„œë²„ ë‚´ë¶€ì—ì„œ ì˜ˆìƒì¹˜ ëª»í•œ ì˜¤ë¥˜ ë°œìƒ | ë‹´ë‹¹ ê°œë°œìì—ê²Œ ë¬¸ì˜í•´ì£¼ì„¸ìš”. ìš”ì²­í•œ APIì™€ ë°ì´í„°ë¥¼ í•¨ê»˜ ì „ë‹¬í•˜ë©´ ë„ì›€ì´ ë©ë‹ˆë‹¤. |

        </details>
      operationId: ì„œë²„_ìƒíƒœ_ì²´í¬_2xx
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                ì„œë²„_ìƒíƒœ_ì²´í¬_2xx:
                  value: |-
                    {
                      "message" : "OK",
                      "data" : null
                    }
  /users:
    put:
      tags:
      - User
      summary: íšŒì› ì •ë³´ ìˆ˜ì •
      description: "## íšŒì› ì •ë³´ ìˆ˜ì • ê¸°ëŠ¥ \n### ì‚¬ìš©ë²• \n- í•„ë“œì˜ validationì„ í™•ì¸í•´ì£¼ì„¸ìš”.\n"
      operationId: íšŒì›_ì •ë³´_ì—…ë°ì´íŠ¸_
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/UpdateUser"
            examples:
              íšŒì›_ì •ë³´_ì—…ë°ì´íŠ¸_2xx:
                value: "{\"name\":\"ì´ë¦„ë°”ê¾¸ê¸°\"}"
              íšŒì›_ì •ë³´_ì—…ë°ì´íŠ¸_4xx_ìš”ì²­_ë°ì´í„°_ìœ íš¨ì„±_ê²€ì‚¬_ì‹¤íŒ¨:
                value: "{\"name\":\"\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                íšŒì›_ì •ë³´_ì—…ë°ì´íŠ¸_2xx:
                  value: |-
                    {
                      "message" : "OK",
                      "data" : 1
                    }
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                íšŒì›_ì •ë³´_ì—…ë°ì´íŠ¸_4xx_ìš”ì²­_ë°ì´í„°_ìœ íš¨ì„±_ê²€ì‚¬_ì‹¤íŒ¨:
                  value: |-
                    {
                      "message" : "nameì˜ í•„ë“œ ê°’ ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤.",
                      "data" : null
                    }
    post:
      tags:
      - User
      summary: íšŒì› ê°€ì…
      description: "## íšŒì› ê°€ì… ê¸°ëŠ¥ \n### ì‚¬ìš©ë²• \n- í•„ë“œì˜ validationì„ í™•ì¸í•´ì£¼ì„¸ìš”.\n- ì•„ì´ë””ì™€ ì´ë©”ì¼\
        \ ì¤‘ë³µ ì²´í¬ ì™„ë£Œ í›„ ì§„í–‰í•´ì£¼ì„¸ìš”."
      operationId: íšŒì›ê°€ì…_
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/RegisterUser"
            examples:
              íšŒì›ê°€ì…_2xx:
                value: "{\"loginId\":\"test1\",\"password\":\"test1@1234\",\"email\"\
                  :\"test1@gmail.com\",\"name\":\"í™ê¸¸ë™\"}"
              íšŒì›ê°€ì…_4xx_ì•„ì´ë””_ì¤‘ë³µ:
                value: "{\"loginId\":\"test1\",\"password\":\"test1@1234\",\"email\"\
                  :\"test1@gmail.com\",\"name\":\"í™ê¸¸ë™\"}"
              íšŒì›ê°€ì…_4xx_ìš”ì²­_ë°ì´í„°_ìœ íš¨ì„±_ê²€ì‚¬_ì‹¤íŒ¨:
                value: "{\"loginId\":\"test1\",\"password\":\"1234\",\"email\":\"\
                  test1@gmail.com\",\"name\":\"í™ê¸¸ë™\"}"
              íšŒì›ê°€ì…_4xx_ì´ë©”ì¼_ì¤‘ë³µ:
                value: "{\"loginId\":\"test1\",\"password\":\"test1@1234\",\"email\"\
                  :\"test1@gmail.com\",\"name\":\"í™ê¸¸ë™\"}"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                íšŒì›ê°€ì…_2xx:
                  value: |-
                    {
                      "message" : "OK",
                      "data" : 0
                    }
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                íšŒì›ê°€ì…_4xx_ì•„ì´ë””_ì¤‘ë³µ:
                  value: |-
                    {
                      "message" : "ì´ë¯¸ ì‚¬ìš© ì¤‘ì¸ ì•„ì´ë””ì…ë‹ˆë‹¤.",
                      "data" : null
                    }
                íšŒì›ê°€ì…_4xx_ì´ë©”ì¼_ì¤‘ë³µ:
                  value: |-
                    {
                      "message" : "ì´ë¯¸ ì‚¬ìš© ì¤‘ì¸ ì´ë©”ì¼ì…ë‹ˆë‹¤.",
                      "data" : null
                    }
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                íšŒì›ê°€ì…_4xx_ìš”ì²­_ë°ì´í„°_ìœ íš¨ì„±_ê²€ì‚¬_ì‹¤íŒ¨:
                  value: |-
                    {
                      "message" : "passwordì˜ í•„ë“œ ê°’ ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤.",
                      "data" : null
                    }
    delete:
      tags:
      - User
      summary: íšŒì› íƒˆí‡´
      description: "## íšŒì› íƒˆí‡´ ê¸°ëŠ¥ \n### ì°¸ê³  \n- ì„œë²„ì˜ ê¶Œí•œ ì •ë³´ ë° í´ë¼ì´ì–¸íŠ¸ì˜ ê¶Œí•œ ì¿ í‚¤ë¥¼ ì´ˆê¸°í™” í•©ë‹ˆë‹¤.\n"
      operationId: íšŒì›_íƒˆí‡´_2xx
      responses:
        "200":
          description: "200"
          headers:
            Set-Cookie:
              description: ì¿ í‚¤ ì´ˆê¸°í™”ì…ë‹ˆë‹¤.
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                íšŒì›_íƒˆí‡´_2xx:
                  value: |-
                    {
                      "message" : "OK",
                      "data" : null
                    }
  /users/password:
    patch:
      tags:
      - User
      summary: ë¹„ë°€ë²ˆí˜¸ ì—…ë°ì´íŠ¸
      description: "## ë¹„ë°€ë²ˆí˜¸ ì—…ë°ì´íŠ¸ ê¸°ëŠ¥ \n### ì‚¬ìš©ë²• \n- í•„ë“œì˜ validationì„ í™•ì¸í•´ì£¼ì„¸ìš”.\n"
      operationId: ë¹„ë°€ë²ˆí˜¸_ì—…ë°ì´íŠ¸_
      requestBody:
        content:
          application/json;charset=UTF-8:
            schema:
              $ref: "#/components/schemas/ChangePassword"
            examples:
              ë¹„ë°€ë²ˆí˜¸_ì—…ë°ì´íŠ¸_2xx:
                value: "{\"password\":\"test1@1234\",\"newPassword\":\"newPassword1234@\"\
                  }"
              ë¹„ë°€ë²ˆí˜¸_ì—…ë°ì´íŠ¸_4xx_ìš”ì²­_ë°ì´í„°_ìœ íš¨ì„±_ê²€ì‚¬_ì‹¤íŒ¨:
                value: "{\"password\":\"test1@1234\",\"newPassword\":\"1234\"}"
              ë¹„ë°€ë²ˆí˜¸_ì—…ë°ì´íŠ¸_4xx_ê¸°ì¡´_ë¹„ë°€ë²ˆí˜¸ê°€_ì˜¬ë°”ë¥´ì§€_ì•ŠìŒ:
                value: "{\"password\":\"test1@1234\",\"newPassword\":\"newPassword1234@\"\
                  }"
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                ë¹„ë°€ë²ˆí˜¸_ì—…ë°ì´íŠ¸_2xx:
                  value: |-
                    {
                      "message" : "OK",
                      "data" : null
                    }
        "400":
          description: "400"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                ë¹„ë°€ë²ˆí˜¸_ì—…ë°ì´íŠ¸_4xx_ìš”ì²­_ë°ì´í„°_ìœ íš¨ì„±_ê²€ì‚¬_ì‹¤íŒ¨:
                  value: |-
                    {
                      "message" : "newPasswordì˜ í•„ë“œ ê°’ ìœ íš¨í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤.",
                      "data" : null
                    }
                ë¹„ë°€ë²ˆí˜¸_ì—…ë°ì´íŠ¸_4xx_ê¸°ì¡´_ë¹„ë°€ë²ˆí˜¸ê°€_ì˜¬ë°”ë¥´ì§€_ì•ŠìŒ:
                  value: |-
                    {
                      "message" : "ë¹„ë°€ë²ˆí˜¸ê°€ ì¼ì¹˜í•˜ì§€ ì•ŠìŠµë‹ˆë‹¤.",
                      "data" : null
                    }
  /users/profile:
    get:
      tags:
      - User
      summary: í”„ë¡œí•„ ì¡°íšŒ
      description: í”„ë¡œí•„ ì¡°íšŒ
      operationId: í”„ë¡œí•„_ì¡°íšŒ_2xx
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                í”„ë¡œí•„_ì¡°íšŒ_2xx:
                  value: |-
                    {
                      "message" : "OK",
                      "data" : {
                        "loginId" : "test1",
                        "email" : "test1@gmail.com",
                        "name" : "í™ê¸¸ë™"
                      }
                    }
  /users/{userId}:
    get:
      tags:
      - User
      summary: ê³µê°œ í”„ë¡œí•„ ì¡°íšŒ
      description: ê³µê°œ í”„ë¡œí•„ ì¡°íšŒ
      operationId: ê³µê°œ_í”„ë¡œí•„_ì¡°íšŒ_
      parameters:
      - name: userId
        in: path
        description: ""
        required: true
        schema:
          type: string
      responses:
        "404":
          description: "404"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                ê³µê°œ_í”„ë¡œí•„_ì¡°íšŒ_4xx_notfound:
                  value: |-
                    {
                      "message" : "Userì„(ë¥¼) ì°¾ì„ ìˆ˜ ì—†ìŠµë‹ˆë‹¤.",
                      "data" : null
                    }
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                ê³µê°œ_í”„ë¡œí•„_ì¡°íšŒ_2xx:
                  value: |-
                    {
                      "message" : "OK",
                      "data" : {
                        "email" : "test1@gmail.com",
                        "name" : "í™ê¸¸ë™"
                      }
                    }
  /users/email/exists:
    get:
      tags:
      - User
      summary: ì´ë©”ì¼ ì¤‘ë³µ ì²´í¬
      description: "## ì´ë©”ì¼ ì¤‘ë³µ ì²´í¬ ê¸°ëŠ¥ \n### ì‚¬ìš©ë²• \n- ì´ë©”ì¼ì„ ì¿¼ë¦¬ íŒŒë¼ë¯¸í„°ë¡œ ì „ì†¡í•©ë‹ˆë‹¤.\n- 200ì‘ë‹µì´ë¼ë©´\
        \ ì‚¬ìš© ê°€ëŠ¥í•©ë‹ˆë‹¤."
      operationId: ì´ë©”ì¼_ì¤‘ë³µ_ì²´í¬_
      parameters:
      - name: email
        in: query
        description: ê²€ì¦ ëŒ€ìƒ ì´ë©”ì¼
        required: true
        schema:
          type: string
      responses:
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                ì´ë©”ì¼_ì¤‘ë³µ_ì²´í¬_4xx_email_ì¤‘ë³µ:
                  value: |-
                    {
                      "message" : "ì´ë¯¸ ì‚¬ìš© ì¤‘ì¸ ì´ë©”ì¼ì…ë‹ˆë‹¤.",
                      "data" : null
                    }
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                ì´ë©”ì¼_ì¤‘ë³µ_ì²´í¬_2xx:
                  value: |-
                    {
                      "message" : "OK",
                      "data" : null
                    }
  /users/login-id/exists:
    get:
      tags:
      - User
      summary: ì•„ì´ë”” ì¤‘ë³µ ì²´í¬
      description: "## ì•„ì´ë”” ì¤‘ë³µ ì²´í¬ ê¸°ëŠ¥ \n### ì‚¬ìš©ë²• \n- ì•„ì´ë””ë¥¼ ì¿¼ë¦¬ íŒŒë¼ë¯¸í„°ë¡œ ì „ì†¡í•©ë‹ˆë‹¤.\n- 200ì‘ë‹µì´ë¼ë©´\
        \ ì‚¬ìš© ê°€ëŠ¥í•©ë‹ˆë‹¤."
      operationId: ì•„ì´ë””_ì¤‘ë³µ_ì²´í¬_
      parameters:
      - name: loginId
        in: query
        description: ê²€ì¦ ëŒ€ìƒ ì•„ì´ë””
        required: true
        schema:
          type: string
      responses:
        "200":
          description: "200"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                ì•„ì´ë””_ì¤‘ë³µ_ì²´í¬_2xx:
                  value: |-
                    {
                      "message" : "OK",
                      "data" : null
                    }
        "409":
          description: "409"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/users486549215"
              examples:
                ì•„ì´ë””_ì¤‘ë³µ_ì²´í¬_4xx_loing-id_ì¤‘ë³µ:
                  value: |-
                    {
                      "message" : "ì´ë¯¸ ì‚¬ìš© ì¤‘ì¸ ì•„ì´ë””ì…ë‹ˆë‹¤.",
                      "data" : null
                    }
components:
  schemas:
    RegisterUser:
      title: RegisterUser
      required:
      - email
      - loginId
      - name
      - password
      type: object
      properties:
        password:
          type: string
          description: ë¹„ë°€ë²ˆí˜¸ëŠ” íŠ¹ìˆ˜ë¬¸ìë¥¼ í¬í•¨í•œ ì˜ë¬¸ê³¼ ìˆ«ì 8ìë¦¬ ì´ìƒì…ë‹ˆë‹¤.
        loginId:
          type: string
          description: ì•„ì´ë””ëŠ” ì˜ë¬¸ 4ìë¦¬ ì´ìƒì…ë‹ˆë‹¤.
        name:
          type: string
          description: ì‚¬ìš©ì ì´ë¦„ì…ë‹ˆë‹¤.
        email:
          type: string
          description: ì´ë©”ì¼ í˜•ì‹ì„ ì§€ì¼œì£¼ì„¸ìš”.
    auths-reissue515442717:
      required:
      - data
      - message
      type: object
      properties:
        message:
          type: string
          description: ë©”ì„¸ì§€
    LoginResponseDto:
      title: LoginResponseDto
      required:
      - data
      - message
      type: object
      properties:
        message:
          type: string
          description: ë©”ì„¸ì§€
    ChangePassword:
      title: ChangePassword
      required:
      - newPassword
      - password
      type: object
      properties:
        password:
          type: string
          description: ê¸°ì¡´ ë¹„ë°€ë²ˆí˜¸ì…ë‹ˆë‹¤.
        newPassword:
          type: string
          description: ìƒˆë¡œìš´ ë¹„ë°€ë²ˆí˜¸ì…ë‹ˆë‹¤.
    LoginRequestDto:
      title: LoginRequestDto
      type: object
    UpdateUser:
      title: UpdateUser
      required:
      - name
      type: object
      properties:
        name:
          type: string
          description: ì‚¬ìš©ì ì´ë¦„ì…ë‹ˆë‹¤.
    users486549215:
      type: object
  securitySchemes:
    JWT:
      type: apiKey
      name: Authorization
      in: header
security:
  - JWT: []  